---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoorder
  template:
    metadata:
      labels:
        app: demoorder
    spec:
      containers:
        - name: demoorder
          image: koshyanish07/demo-order:1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: books.rest.url
              value: http://demobook-git-new:8080/demo-book/rest/books
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
                path: /swagger-ui/
                port: 8081
          resources:
            limits:
                memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demoorder
spec:
  selector:
    app: demoorder
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer