---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demobook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demobook
  template:
    metadata:
      labels:
        app: demobook
    spec:
      containers:
        - name: demobook
          image: koshyanish07/demo-book:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
                path: /swagger-ui/
                port: 8080
          resources:
            limits:
                memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demobook-git-new
spec:
  selector:
    app: demobook
  ports:
    - nodePort: 32003
      port: 80
      targetPort: 8080
  type: NodePort